/* automatically generated by xdrgen from xdr/std_msgs_Bool.xdr
 * xdrgen cvs version: $Revision: 1.7 $ $Date: 2009/01/12 15:54:59 $
 * xdr/std_msgs_Bool.xdr last modified: Thu Nov 11 11:15:54 2010
 */

#ifndef INCstd_msgs_Bool_h
#define INCstd_msgs_Bool_h


struct std_msgs_Bool {
  unsigned int data;
#define std_msgs_Bool_IPC_FORMAT "{uint}"
  static const char *getIPCFormat(void) {
    return std_msgs_Bool_IPC_FORMAT;
  }
};


namespace ipc_bridge
{
    namespace std_msgs
    {
        typedef std_msgs_Bool Bool;
    }
}


#endif /* INCstd_msgs_Bool_h */
